### ISSUE TITLE
How can I update esp-open-sdk  inside the image

### ISSUE THREAD

**Issue by 3dot3** [asmaps/docker-nodemcu-builder#2]
Thx

**Comment by asmaps** [comment]
It will automatically use the latest version of https://github.com/pfalcon/esp-open-sdk on build - if there is a new version and you already have an old one rebuild the image with

```
docker build --no-cache -t nodemcu-builder docker-nodemcu-builder
```

as described in the readme, but with the `--no-cache` option.
